// Copyright 2024 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define WS2812_PWM_DRIVER PWMD4
#define WS2812_PWM_CHANNEL 3
#define WS2812_PWM_PAL_MODE 2
#define WS2812_DMA_STREAM STM32_DMA1_STREAM7
#define WS2812_DMA_CHANNEL 7

#define ENCODER_DIRECTION_FLIP

#define ENABLE_COMPILE_KEYCODE

#define RGB_MATRIX_LED_COUNT 68
#define RGB_MATRIX_TIMEOUT 600000
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
#define RGB_MATRIX_DEFAULT_ON true
#define RGB_MATRIX_DEFAULT_HUE 80
#define RGB_MATRIX_DEFAULT_SAT 200
#define RGB_MATRIX_SLEEP
// #define RGB_MATRIX_DEFAULT_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS

